name: Riverto
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.1+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_media_notification:
    git:
      url: https://github.com/Sj-Projects/flutter_media_notification.git
      ref: master
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  audiotagger: ^1.1.0
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.9+2
  cupertino_icons: ^0.1.3
  des_plugin: ^0.0.3
  email_validator: ^1.0.5
  ext_storage: ^1.0.3
  fluttertoast: ^7.0.2
  gradient_widgets: ^0.5.2
  http: ^0.12.2
  material_design_icons_flutter: 4.0.5345
  path_provider: 
  permission_handler: ^5.0.1+1
  progress_dialog: ^1.2.4
  shared_preferences:
  url_launcher: ^5.5.0
  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-Italic.ttf
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Medium.ttf
# flutter:
#   uses-material-design: true
#   fonts:
#     - family: Less
#       fonts:
#         - asset: fonts/Less.otf
#         - asset: fonts/Less-Light.otf
#         - asset: fonts/Less-Bold.otf
